"""add materials and material quote requests

Revision ID: a737f491c521
Revises: de1d49df553f
Create Date: 2026-07-29 16:43:15.902554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a737f491c521'
down_revision = 'de1d49df553f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('type', sa.Enum('wood', 'plywood', name='materialtype'), nullable=False),
    sa.Column('subtype', sa.String(length=120), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('best_use', sa.String(length=255), nullable=True),
    sa.Column('finish', sa.String(length=120), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('durability_rating', sa.String(length=80), nullable=True),
    sa.Column('waterproof', sa.Boolean(), nullable=False),
    sa.Column('warranty_info', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_slug'), 'materials', ['slug'], unique=True)
    op.create_index(op.f('ix_materials_type'), 'materials', ['type'], unique=False)
    op.create_table('material_quote_requests',
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', name='quoterequeststatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_quote_requests')
    op.drop_index(op.f('ix_materials_type'), table_name='materials')
    op.drop_index(op.f('ix_materials_slug'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
