"""add product video_url

Revision ID: ea79d389c4e6
Revises: 12c732d119ad
Create Date: 2026-07-28 11:49:57.327259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea79d389c4e6'
down_revision = '12c732d119ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'video_url')
    # ### end Alembic commands ###
